cmd/kor/root.go
=> Show help command if no argument was provided

pkg/kor/all.go
Fixes https://github.com/yonahd/kor/issues/23
=> fix: reset the diff between each namespace

README.md, cmd/kor/pdbs.go, pkg/kor/all.go, pkg/kor/pdbs.go
Supports https://github.com/yonahd/kor/issues/15
=> support finding unused Pdbs

.dockerignore, .github/workflows/release.yml, Dockerfile
As discussed in #73, this is a separate PR.
Related issue #74
=> feat: add docker support with workflow to update image

cmd/kor/all.go, cmd/kor/configmaps.go, cmd/kor/deployments.go, cmd/kor/hpas.go, cmd/kor/ingresses.go, cmd/kor/pdbs.go, cmd/kor/pvc.go, cmd/kor/roles.go, cmd/kor/root.go, cmd/kor/secrets.go, cmd/kor/serviceaccounts.go, cmd/kor/services.go, cmd/kor/statefulsets.go, go.mod, pkg/kor/all.go, pkg/kor/confimgmaps.go, pkg/kor/deployments.go, pkg/kor/hpas.go, pkg/kor/ingresses.go, pkg/kor/kor.go, pkg/kor/kor_test.go, pkg/kor/pdbs.go, pkg/kor/pvc.go, pkg/kor/roles.go, pkg/kor/secrets.go, pkg/kor/serviceaccounts.go, pkg/kor/services.go, pkg/kor/statefulsets.go
=> feat: add InCluster config

README.md
Add instructions for installing with `go install` and docker.
=> Update installation instructions to README.md

charts/kor/templates/deployment.yaml, charts/kor/templates/service.yaml, charts/kor/templates/servicemonitor.yaml, charts/kor/values.yaml
=> Update helm charts with deployment support

pkg/kor/ingresses.go
Fixes https://github.com/yonahd/kor/issues/109
=> Fix: validate HTTP field

grafana/dashboard.json
Added all/multi selection filtering for namespaces and filtering by kind.
Added new panel for displaying all unused resources (pie and bar chart options).
Retained original panels at the bottom with added namespace filter options for comparison.
=> Enhanced Dashboard Features: Namespace And Kind Filtering, Resource Visualization.

cmd/kor/exporter.go, pkg/kor/exporter.go
Fix for https://github.com/yonahd/kor/issues/128
=> fix: add filter options in export command

.gitignore, .goreleaser.yml
- adds support for linux arm64
- ignore dist directory in gitignore
=> feat: add support for linux arm64

cmd/kor/root.go, pkg/kor/multi.go
Add filtering functionality when getting multiple resources and move structured formatting to the GetUnusedMulti function.
fixed #138
=> Refactor the GetUnusedMulti function

cmd/kor/root.go, pkg/kor/multi.go
- cleanup unused block
- remove duplicate in case
=> chore: cleanup unused and remove dup

cmd/kor/root.go, pkg/kor/confimgmaps.go, pkg/kor/crds.go, pkg/kor/deployments.go, pkg/kor/hpas.go, pkg/kor/ingresses.go, pkg/kor/kor.go, pkg/kor/pdbs.go, pkg/kor/pvc.go, pkg/kor/roles.go, pkg/kor/secrets.go, pkg/kor/serviceaccounts.go, pkg/kor/services.go, pkg/kor/statefulsets.go
- move to only print unused with a verbose flag
=> fix: make verbose logs a flag

cmd/kor/all.go, cmd/kor/configmaps.go, cmd/kor/crds.go, cmd/kor/deployments.go, cmd/kor/hpas.go, cmd/kor/ingresses.go, cmd/kor/pdbs.go, cmd/kor/pvc.go, cmd/kor/roles.go, cmd/kor/root.go, cmd/kor/secrets.go, cmd/kor/serviceaccounts.go, cmd/kor/services.go, cmd/kor/statefulsets.go, pkg/kor/all.go, pkg/kor/kor.go, pkg/kor/multi.go, pkg/utils/banner.go
fix output banner for yaml and json
=> fix: fix output banner for yaml and json

pkg/kor/delete.go
=> feat: add inUse label prompt for non deleted resources

pkg/kor/delete.go, pkg/kor/ingresses.go
=> fix ingress flag as used

charts/kor/Chart.yaml, charts/kor/templates/cronjob.yaml, charts/kor/templates/deployment.yaml, charts/kor/templates/role.yaml, charts/kor/templates/rolebinding.yaml, charts/kor/templates/secret.yaml, charts/kor/templates/service.yaml, charts/kor/templates/servicemonitor.yaml
For all resources will be useful to have labels.
=> Add labels to all templates.

charts/kor/templates/deployment.yaml, charts/kor/templates/role.yaml, charts/kor/templates/secret.yaml
Hello. My bad, didn't notice a small formatting error.
=> Fix spaces and lost labels

CONTRIBUTING.md, README.md
=> Docs: Added CONTRIBUTING.md

.github/workflows/release.yml
* Update couple of plugins
* Setup and build multi-arch docker image, add arm64 arch
=> feat(image): build multi-arch image

Dockerfile, go.mod
=> chore: upgrade go version to 1.22.0

.github/pull_request_template.md
=> chore: add github pr template

pkg/kor/exceptions/configmaps/configmaps.json, pkg/kor/exceptions/daemonsets/daemonsets.json, pkg/kor/exceptions/storageclasses/storageclasses.json
Please read [CONTRIBUTING.md](CONTRIBUTING.md) for additional information on contributing to this repository!
- Add default AKS exceptions
https://github.com/yonahd/kor/issues/239
=> feat: add AKS exceptions

pkg/kor/exceptions/configmaps/configmaps.json, pkg/kor/exceptions/crds/crds.json, pkg/kor/exceptions/daemonsets/daemonsets.json, pkg/kor/exceptions/serviceaccounts/serviceaccounts.json, pkg/kor/exceptions/services/services.json, pkg/kor/exceptions/storageclasses/storageclasses.json
- add AWS EKS false positives
https://github.com/yonahd/kor/issues/236
=> feat: add AWS EKS defaults

charts/kor/templates/cronjob.yaml
Fix missing `labels` key on cronjob.yaml that cause YAML parse error when run `helm` command.
=> fix(helm): Add missing labels key in metadata

.github/workflows/exceptions-json-sort.yml, pkg/kor/exceptions/clusterroles/clusterroles.json, pkg/kor/exceptions/jobs/jobs.json, pkg/kor/exceptions/secrets/secrets.json
This PR adds a custom GitHub action to validate that the exceptions JSON files are properly sorted.
Once a PR is submitted to `main` branch with modifications under `pkg/kor/exceptions`, this workflow is invoked.
If unsorted JSON files are found, the workflow will fail and provide the contributor with:
1. List of the unsorted files
2. Command to sort all the unsorted files on-demand
Example:
[XX-XX]
The sorting validation is based on `jq` in Bash.
=> style: add GitHub action to validate exceptions JSON sorting

pkg/kor/pdbs.go
=> fix(pdb): fix nil pointer in pdb when selector.matchLabels is nil

charts/kor/Chart.yaml, charts/kor/README.md
=> chore: update chart version pre-release

charts/kor/Chart.yaml, charts/kor/README.md, pkg/kor/multi_test.go
Bump Helm chart version - pre-release
=> Chart bump 0.5.5

ADOPTERS.md
Please read [CONTRIBUTING.md](CONTRIBUTING.md) for additional information on contributing to this repository!
This adds an adopters file to allow teams to display their use cases an give us the motivation to keep building this for the community.
=> Docs: Create ADOPTERS.md

ADOPTERS.md
=> added Ataccama to adopters file

charts/kor/Chart.yaml, charts/kor/README.md
=> chore: prerelease bump
